#!/bin/sh

kmod_enabled() {
	return 0
}

kmod_run() {
	mount -t sysfs sysfs -o nosuid,nodev,noexec /sys

	find /sys -name modalias | while read m; do
		modalias=$(cat "$m")
		modprobe -v "$modalias" 2> /dev/null
	done

	modprobe -v nvme

	for c in /etc/modules-load.d/??-*.conf; do
		[ ! -f "$c" ] && continue
		for m in $(cat $c); do
			modprobe "$m"
			echo "Kernel module loaded from ramdisk: $m - result: $?" > /dev/kmsg
		done
	done
}
