#@TYPE: Machine
#@NAME: i.MX6SoloX Blaze Board
#@SOC: i.MX6SX
#@DESCRIPTION: Machine configuration for the i.MX6SoloX Blaze board, a SABRE-SD derivative

MACHINEOVERRIDES =. "mx6sx:"

require conf/machine/include/imx-base.inc
require conf/machine/include/arm/armv7a/tune-cortexa9.inc

KERNEL_DEVICETREE = "nxp/imx/imx6sx-blaze.dtb"

UBOOT_MAKE_TARGET = "u-boot.imx"
UBOOT_SUFFIX = "imx"

# No U-Boot board port exists; the DDR and control device tree are overridden
# in the u-boot-imx bbappend.
UBOOT_CONFIG ??= "sd"
UBOOT_CONFIG[sd] = "mx6sxsabresd_config,sdcard"

SERIAL_CONSOLES = "115200;ttymxc2"
