#!/bin/bash
# -*- mode: shell-script-mode; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-

source ${_TDX_LAYERS_DIR}/poky/oe-init-build-env "${1:-build-$DISTRO}"
tdx_set_builddir_from_cwd

if tdx_needs_once conf/local.conf; then
  sed -i "/^MACHINE .*/c\MACHINE ?= '$MACHINE'" conf/local.conf
  sed -i "/^DISTRO .*/c\DISTRO ?= '$DISTRO'" conf/local.conf

  tdx_append_once conf/local.conf "# Torizon" <<EOF
# Where to store sources
DL_DIR ?= "${_TDX_OEROOT}/downloads"

# Where to save shared state
SSTATE_DIR ?= "${_TDX_OEROOT}/sstate-cache"
BB_HASHSERVE_DB_DIR ?= "\${SSTATE_DIR}"

# Where to save the build system work output
TMPDIR = "${_TDX_BUILDDIR}/tmp"

# Where to save the packages and images
TI_COMMON_DEPLOY = "${_TDX_BUILDDIR}/deploy"
DEPLOY_DIR = "\${TI_COMMON_DEPLOY}\${@'' if d.getVar('BB_CURRENT_MC') == 'default' else '/\${BB_CURRENT_MC}'}"

# ease up disk space requirements
INHERIT += "rm_work"

# Torizon
include conf/machine/include/\${MACHINE}.inc
EOF

  tdx_append_license_flags conf/local.conf synaptics-killswitch

fi

# When building on integration, ensure use-head-next is set so you always get
# the newest software (u-boot, kernel, aktualizr-torizon, etc). Idempotent, so
# it also applies when local.conf already existed from a previous run.
tdx_apply_integration_override conf/local.conf

tdx_append_once conf/bblayers.conf "# Torizon" <<EOF
OEROOT := "\${@os.path.abspath(os.path.dirname(d.getVar('FILE', True)))}/../.."

# Intel
BBLAYERS += "\${OEROOT}/layers/meta-intel"
# Torizon
BBLAYERS += "\${OEROOT}/layers/meta-toradex-torizon"
# Torizon deps
BBLAYERS += "\${OEROOT}/layers/meta-updater"
BBLAYERS += "\${OEROOT}/layers/meta-virtualization"
# meta-updater and meta-virtualization deps
BBLAYERS += "\${OEROOT}/layers/meta-openembedded/meta-filesystems"
BBLAYERS += "\${OEROOT}/layers/meta-openembedded/meta-python"
BBLAYERS += "\${OEROOT}/layers/meta-openembedded/meta-oe"
BBLAYERS += "\${OEROOT}/layers/meta-openembedded/meta-networking"
EOF

tdx_print_banner "Common Torizon OS" no
