#!/bin/bash
# -*- mode: shell-script-mode; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
#
# Copyright (C) 2012-13 O.S. Systems Software LTDA.
# Copyright (C) 2017 Open Source Foundries Ltd.
# Authored-by:  Otavio Salvador <otavio@ossystems.com.br>
# Adopted to Angstrom:  Khem Raj <raj.khem@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

_TDX_OEROOT=$(pwd)
cd "$_TDX_OEROOT"
if [ -n "$ZSH_VERSION" ]; then
    setopt sh_word_split
    setopt clobber
elif [ -n "$BASH_VERSION" ]; then
    set +o noclobber
fi

if [ -z "${SDKMACHINE}" ]; then
    SDKMACHINE='x86_64'
fi

_TDX_MANIFESTS="${_TDX_OEROOT}"/.repo/manifests
_TDX_SCRIPTS="${_TDX_OEROOT}"/layers/meta-toradex-torizon/scripts

# We can be called with only 1 parameter max (build folder)
_TDX_BUILDDIR=${1:-build-$DISTRO}
# If current BUILDDIR is relative then prepend OEROOT
case ${_TDX_BUILDDIR} in
    /* ) ;;
    *  ) _TDX_BUILDDIR=$(readlink -f ${_TDX_BUILDDIR});;
esac
# Get rid of double slash. sed calls in OE staging_processfixme
# seems to have troubles if this makes it into OE variables.
_TDX_BUILDDIR=${_TDX_BUILDDIR%%/}

# Set BBPATH for recipetool
BBPATH=${_TDX_BUILDDIR}

# Clean up PATH, because if it includes tokens to current directories somehow,
# wrong binaries can be used instead of the expected ones during task execution
PATH=$(echo "${PATH}" | sed 's/\(:.\|:\)*:/:/g;s/^.\?://;s/:.\?$//')
PATH="${_TDX_OEROOT}/bitbake/bin:${_TDX_OEROOT}/.repo/repo:${PATH}"
PATH="${_TDX_OEROOT}/layers/openembedded-core/bitbake/bin:${PATH}"
PATH="${_TDX_OEROOT}/layers/openembedded-core/scripts:${PATH}"
# Remove duplicate path entries
PATH=$(echo "$PATH" |
       awk -F: '{for (i=1;i<=NF;i++) { if ( !x[$i]++ ) printf("%s:",$i); }}' |
       sed 's/:$//')

BB_ENV_PASSTHROUGH_ADDITIONS_OE="MACHINE DISTRO TCMODE TCLIBC HTTP_PROXY http_proxy \
HTTPS_PROXY https_proxy FTP_PROXY ftp_proxy FTPS_PROXY ftps_proxy ALL_PROXY \
all_proxy NO_PROXY no_proxy SSH_AGENT_PID SSH_AUTH_SOCK BB_SRCREV_POLICY \
SDKMACHINE BB_NUMBER_THREADS BB_NO_NETWORK PARALLEL_MAKE GIT_PROXY_COMMAND \
SOCKS5_PASSWD SOCKS5_USER SCREENDIR STAMPS_DIR BBPATH_EXTRA BB_SETSCENE_ENFORCE"

BB_ENV_PASSTHROUGH_ADDITIONS="$(echo $BB_ENV_PASSTHROUGH_ADDITIONS $BB_ENV_PASSTHROUGH_ADDITIONS_OE | tr ' ' '\n' | LC_ALL=C sort --unique | tr '\n' ' ')"

export PATH
export _TDX_BUILDDIR
export BBPATH
export BB_ENV_PASSTHROUGH_ADDITIONS

_TDX_AUTO_CONF_CREATED=0
mkdir -p "${_TDX_BUILDDIR}"/conf && cd "${_TDX_BUILDDIR}"
if [ -f "conf/auto.conf" ]; then
    oldmach=$(egrep "^MACHINE \?=" "conf/auto.conf" |
             sed -e 's%^MACHINE ?= %%' | sed -e 's/^"//' -e 's/"$//')
    olddisto=$(egrep "^DISTRO \?=" "conf/auto.conf" |
             sed -e 's%^DISTRO ?= %%' | sed -e 's/^"//' -e 's/"$//')
    eulaacpt=$(egrep "^\s*ACCEPT_EULA_${MACHINE}\s*=\s*\".*\"" conf/local.conf |
             sed -e "s%^\s*ACCEPT_EULA_${MACHINE}\s*=\s*%%" | sed -e 's/^"//' -e 's/"$//')

    _TDX_AUTO_CONF_CREATED=1
fi

if [ -e conf/checksum -a "${MACHINE}" = "$oldmach" -a "${DISTRO}" = "$olddisto" -a "${EULA}" = "$eulaacpt" ]; then
    if sha512sum --quiet -c conf/checksum >/dev/null 2>&1; then
        return 0
    fi
fi

# Evaluate new checksum and regenerate the conf files
sha512sum "${_TDX_SCRIPTS}"/lib/setup-devices/setup-environment-nvidia 2>&1 > conf/checksum

if [ ! -f "conf/local.conf" ]; then
    cp "${_TDX_SCRIPTS}"/../conf/template/local.conf conf/local.conf
fi
ln -sf "${_TDX_MANIFESTS}"/README.md README.md
ln -sf "${_TDX_MANIFESTS}" "${_TDX_OEROOT}"/layers/

if [ ! -f "conf/bblayers.conf" ]; then
    cat > conf/bblayers.conf <<EOF
# Torizon
# LAYER_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
LCONF_VERSION = "7"
OEROOT := "\${@os.path.abspath(os.path.dirname(d.getVar('FILE', True)))}/../.."

BBPATH = "\${TOPDIR}"

BBFILES = ""

# These layers hold recipe metadata not found in OE-core, but lack any machine or distro content
BASELAYERS ?= " \\
  \${OEROOT}/layers/meta-openembedded/meta-oe \\
  \${OEROOT}/layers/meta-openembedded/meta-networking \\
  \${OEROOT}/layers/meta-openembedded/meta-filesystems \\
  \${OEROOT}/layers/meta-openembedded/meta-python \\
  \${OEROOT}/layers/meta-openembedded/meta-perl \\
  \${OEROOT}/layers/meta-virtualization \\
  \${OEROOT}/layers/meta-updater \\
"

# These layers hold machine specific content, aka Board Support Packages
BSPLAYERS ?= " \\
  \${OEROOT}/layers/meta-yocto/meta-yocto-bsp \\
  \${OEROOT}/layers/meta-yocto/meta-poky \\
  \${OEROOT}/layers/meta-tegra \\
"

# Add your overlay location to EXTRALAYERS
# Make sure to have a conf/layers.conf in there
EXTRALAYERS ?= ""

BBLAYERS = " \\
  \${OEROOT}/layers/meta-toradex-torizon \\
  \${BASELAYERS} \\
  \${BSPLAYERS} \\
  \${EXTRALAYERS} \\
  \${OEROOT}/layers/openembedded-core/meta \\
"
EOF
fi

if [ "$_TDX_AUTO_CONF_CREATED" = "0" ]; then
    cat >> conf/auto.conf <<EOF
DISTRO ?= "${DISTRO}"
MACHINE ?= "${MACHINE}"
SDKMACHINE ?= "${SDKMACHINE}"

# Extra options that can be changed by the user
INHERIT += "rm_work"
EOF
else
    sed -i "s/^DISTRO ?= \"[^\"]*\"$/DISTRO ?= \"${DISTRO}\"/" conf/auto.conf
    sed -i "s/^MACHINE ?= \"[^\"]*\"$/MACHINE ?= \"${MACHINE}\"/" conf/auto.conf
    sed -i "s/^SDKMACHINE ?= \"[^\"]*\"$/SDKMACHINE ?= \"${SDKMACHINE}\"/" conf/auto.conf
fi

cat > conf/site.conf <<_EOF
SCONF_VERSION = "1"

# Where to store sources
DL_DIR ?= "${_TDX_OEROOT}/downloads"

# Where to save shared state
SSTATE_DIR ?= "${_TDX_OEROOT}/sstate-cache"

# Where to save the build system work output
TMPDIR = "${_TDX_BUILDDIR}/tmp"

# Where to save the packages and images
_COMMON_DEPLOY = "${_TDX_BUILDDIR}/deploy"
DEPLOY_DIR = "\${_COMMON_DEPLOY}\${@'' if d.getVar('BB_CURRENT_MC') == 'default' else '/\${BB_CURRENT_MC}'}"

# Go through the Firewall
#HTTP_PROXY = "http://${PROXYHOST}:${PROXYPORT}/"
_EOF

cat <<EOF

Welcome to Toradex Torizon OS

For more information about OpenEmbedded see their website:

    http://www.openembedded.org/

Your build environment has been configured with:

    MACHINE = ${MACHINE}
    SDKMACHINE = ${SDKMACHINE}
    DISTRO = ${DISTRO}

You can now run 'bitbake <target>'

Some of common targets are:

    torizon-docker
    torizon-minimal
    torizon-podman

EOF
