#!/bin/bash

if ! grep -q "# Torizon" /build/conf/local.conf; then
  sed -i "/^MACHINE .*/c\MACHINE = '$MACHINE'" /build/conf/local.conf
  sed -i "/^DISTRO .*/c\DISTRO = '$DISTRO'" /build/conf/local.conf

  cat <<EOF >>/build/conf/local.conf
# Where to store sources
DL_DIR = "/build/downloads"

# Where to save shared state
SSTATE_DIR = "/build/sstate-cache"

# Where to save the build system work output
TMPDIR = "/build/tmp"

# Where to save the packages and images
DEPLOY_DIR = "/build/deploy"

# Torizon
include conf/machine/include/\${MACHINE}.inc
EOF
fi

if ! grep -q "# Torizon" /build/conf/bblayers.conf; then 
  cat <<EOF >>/build/conf/bblayers.conf
# Torizon
BBLAYERS += "\${TOPDIR}/../work/meta-toradex-torizon"
# Torizon deps
BBLAYERS += "\${TOPDIR}/../work/meta-updater"
BBLAYERS += "\${TOPDIR}/../work/meta-virtualization"
# meta-updater and meta-virtualization deps
BBLAYERS += "\${TOPDIR}/../work/meta-openembedded/meta-filesystems"
BBLAYERS += "\${TOPDIR}/../work/meta-openembedded/meta-python"
BBLAYERS += "\${TOPDIR}/../work/meta-openembedded/meta-networking"

OEROOT := "\${@os.path.abspath(os.path.dirname(d.getVar('FILE', True)))}/../.."
EOF
fi

cat <<EOF

Welcome to Common Torizon OS

For more information about OpenEmbedded see their website:

    http://www.openembedded.org/

Your build environment has been configured with:

    MACHINE = ${MACHINE}
    DISTRO = ${DISTRO}

You can now run 'bitbake <target>'

Some of common targets are:

    torizon-docker
    torizon-minimal
    torizon-podman

EOF
