#!/bin/sh
# Copyright (c) Fathi Boudra <fathi.boudra@linaro.org>
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

# must exit on error
set -e
set -o pipefail

# we must be root
[ $(whoami) = "root" ] || { echo "E: You must be root" && exit 1; }

# we must have few tools
SGDISK=$(which sgdisk) || { echo "E: You must have sgdisk" && exit 1; }
FDISK=$(which fdisk) || { echo "E: You must have fdisk" && exit 1; }
PARTX=$(which partx) || { echo "E: You must have partx" && exit 1; }
RESIZE2FS=$(which resize2fs) || { echo "E: You must have resize2fs" && exit 1; }

# find root device
ROOT_DEVICE=$(findmnt --noheadings --output=SOURCE / | cut -d'[' -f1)
# prune root device (for example UUID)
ROOT_DEVICE=$(realpath ${ROOT_DEVICE})
# get the partition number and type
INFO=$(udevadm info --query=property --name=${ROOT_DEVICE})
PART_ENTRY_NUMBER=$(echo "${INFO}" | grep '^ID_PART_ENTRY_NUMBER=' | cut -d'=' -f2)
PART_ENTRY_NAME=$(echo "${INFO}" | grep '^ID_PART_ENTRY_NAME=' | cut -d'=' -f2 || true)

# in case the root device is not on a partitioned media
if [ "x$PART_ENTRY_NUMBER" = "x" ]; then
	${RESIZE2FS} "${ROOT_DEVICE}"
	exit 0
fi

PART_TABLE_TYPE=$(echo "${INFO}" | grep '^ID_PART_TABLE_TYPE=' | cut -d'=' -f2)
# find the block device
DEVICE=$(udevadm info --query=path --name=${ROOT_DEVICE} | awk -F'/' '{print $(NF-1)}')
DEVICE="/dev/${DEVICE}"

if [ "$PART_TABLE_TYPE" = "gpt" ]; then
	# sgdisk speaks the device's logical sector size, so the grow is
	# correct on 4Kn media where blockdev/udev report 512-byte units.
	# Read start and attribute flags before altering the table: the
	# delete/recreate below resets both, and the attributes carry the
	# legacy-BIOS-bootable flag (WIC --active) that U-Boot's distro_bootcmd
	# scan uses to find the rootfs.
	PART_INFO=$(${SGDISK} --info=${PART_ENTRY_NUMBER} ${DEVICE})
	START=$(echo "${PART_INFO}" | awk '/^First sector:/ {print $3}')
	ATTRS=$(echo "${PART_INFO}" | awk '/^Attribute flags:/ {print $3}')
	# Recreating at an empty or zero start would place the partition at
	# sgdisk's default offset, not the original, and corrupt the rootfs.
	case "${START}" in
		''|0|*[!0-9]*)
			echo "E: could not read first sector of partition ${PART_ENTRY_NUMBER} on ${DEVICE}" >&2
			exit 1
			;;
	esac
	${SGDISK} --move-second-header ${DEVICE}
	# end 0 = grow to the last available sector
	${SGDISK} --delete=${PART_ENTRY_NUMBER} --new=${PART_ENTRY_NUMBER}:${START}:0 ${DEVICE}
	if [ -n "${PART_ENTRY_NAME}" ]; then
		${SGDISK} --change-name=${PART_ENTRY_NUMBER}:"${PART_ENTRY_NAME}" ${DEVICE}
	fi
	if [ -n "${ATTRS}" ]; then
		${SGDISK} --attributes=${PART_ENTRY_NUMBER}:=:${ATTRS} ${DEVICE}
	fi
else
	# Use fdisk to repartition
	# fdisk uses a ram image of the parition table until a write is performed
	# so the sequence is to delete the partition and recreate it at the same
	# starting point but making it the size of the available disk.
	#
	SIZE=$(blockdev --getsz ${DEVICE})
	END=$((${SIZE} - 1))
	PARTOF=$(echo "${INFO}" | grep '^ID_PART_ENTRY_OFFSET=' | cut -d'=' -f2)
	echo -e "d\n${PART_ENTRY_NUMBER}\nn\np\n${PART_ENTRY_NUMBER}\n${PARTOF}\n${END}\nw\n" | ${FDISK} ${DEVICE}
fi

${PARTX} -u ${DEVICE}
${RESIZE2FS} "${ROOT_DEVICE}"
